//hello test saving
public class Class101 {

    public void fff()
    {
        Integer[] myInts = new Integer[]{1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
        Integer[] myInts2 = new Integer[]{1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
            
        Datetime ONn =  Datetime.newInstance(2015,09,30,0,0,0);
        
        {}
        
        for (Integer i :  myInts);
        while(false);
        
        {}
    }
}